# Project information
site_name: CSV Table Schema
site_description: 'Documentation for CSV Table Schema'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://csv-table-schema.github.io/'

# Copyright
copyright: © 2022 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'On GitHub'
repo_url: 'https://github.com/csv-table-schema/csv-table-schema.github.io'

# Theming
theme: 
    name: material
    language: en
    features:
        - navigation.instant
    palette:
        primary: 'indigo'
        accent: 'amber'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html
    
# Plugins
plugins:
    - search
    - minify:
        minify_html: true

# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Introduction: index.md
- Specification: specification.md
